### ISSUE TITLE
create app with 3 screens: login, home, game

### ISSUE THREAD

**Issue by shacharoz** [shacharoz/Learning_Programming_Basics_With_Python#10]
login:
name click 

home:
2 buttons: restart ; continue 

game:
something

**Comment by ghost** [comment]
I think that you forgot to commit the latest gui tests we've done last time.

**Comment by shacharoz** [comment]
try now . let me know


Shachar Oz
Design & Business for
Emergent Tech Products

FLUX-Strategic Design <http://flux-experiences.com/design/> | Portfolio
<https://www.behance.net/shacharoz>
+972-54-233-8020  | +39-351-519-0003
